FRAME_WIDTH = 640
FRAME_HEIGHT = 480
MIDDLE_RANGE_LEFT = 220
MIDDEL_RANGE_RIGHT = 420

REC_LENGTH = 120  # 录像长度
REC_FREQ = 15  # 录像帧率

DEFAULT_SHOOT_DELAY = 5

WEB_DEBUG = True

SERVER = "https://wolf.myseu.cn/itenserv"

